[Utils] Expand docker images, add check-all
Expands docker-utils image support to all three Ubuntu versions on which
Swift is built. Adds a check-all script that uses docker to build and
test llbuild in all supported images.

diff --git a/utils/build-and-test b/utils/build-and-test
--- a/utils/build-and-test
+++ b/utils/build-and-test
@@ -2,19 +2,16 @@
 
 set -e
 
-TARGETS=${TARGETS:-"14.04 16.04 18.04"}
+if [ "$#" -ne 1 ]; then
+    echo "$0: error: usage: $0 <target-platform>"
+    exit 1
+fi
 
-# Check for required dependencies
-for c in pip docker; do
-  command -v $c >/dev/null 2>&1 || { echo >&2 "error: $c required, but not found"; exit 1; }
-done
+TARGET=$1
+SRCROOT="${PWD}"
+BUILDROOT=".build/.ci/${TARGET}"
 
-# Ensure the docker dependencies are installed
-pip install -r utils/docker/requirements.txt
-
-# Build all the base images
-for TARGET in ${TARGETS}; do
-    utils/docker/docker-utils build --target=${TARGET}
-done
-
-
+mkdir -p "${BUILDROOT}"
+cd "${BUILDROOT}"
+cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ "${SRCROOT}"
+ninja test
diff --git a/utils/check-all b/utils/check-all
--- a/utils/check-all
+++ b/utils/check-all
@@ -1,32 +1,19 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 
-SRCROOT="$(realpath $(pwd))"
-OBJROOT="/tmp/llbuild-cov.obj"
+TARGETS=${TARGETS:-"14.04 16.04 18.04"}
 
-# Run a build and test cycle with --coverage enabled to generate the .gcda data.
-if false; then
-    echo "note: building with xcodebuild into '${OBJROOT}'..."
-    time xcodebuild \
-        -scheme test \
-        OBJROOT="${OBJROOT}" \
-        SYMROOT="${OBJROOT}/sym" \
-        DSTROOT="${OBJROOT}/dst" \
-        CCHROOT="${OBJROOT}/cch" \
-        OTHER_CFLAGS="--coverage" OTHER_LDFLAGS="--coverage" &> /tmp/llbuild-cov.log
-else
-    echo "note: building with llbuild into '${OBJROOT}'"
-    mkdir -p ${OBJROOT}
-    (cd ${OBJROOT} &&
-     cmake -G Ninja -DCMAKE_CXX_FLAGS=--coverage -DCMAKE_CXX_COMPILER=/tmp/apple-clang-r442221-t20150326_090132-b26188/usr/bin/clang++ ${SRCROOT} &&
-     xcrun llbuild ninja build --chdir ${OBJROOT} test) &> /tmp/llbuild-cov.log
-fi
+# Check for required dependencies
+for c in pip docker; do
+  command -v $c >/dev/null 2>&1 || { echo >&2 "error: $c required, but not found"; exit 1; }
+done
 
-# Use zcov to generate a coverage report.
-rm -rf build/llbuild.zcov build/llbuild-cov
-mkdir -p build/llbuild-cov
-zcov scan build/llbuild.zcov "${OBJROOT}"
-zcov summarize --root "${SRCROOT}" --prune "/utils/" --prune "/unittests/" build/llbuild.zcov
-zcov genhtml --root "${SRCROOT}" --prune "/utils/" --prune "/unittests/" --hide-branches build/llbuild.zcov build/llbuild-cov
+# Ensure the docker dependencies are installed
+pip install -r utils/docker/requirements.txt
 
+# Check all targets
+for TARGET in ${TARGETS}; do
+    utils/docker/docker-utils build --target=${TARGET}
+    utils/docker/docker-utils run --target=${TARGET} utils/build-and-test ubuntu-${TARGET}
+done
